### ISSUE TITLE
SeriesMgr crashes on loading race under Windows

### ISSUE THREAD

**Issue by kimble4** [esitarski/CrossMgr#108]
With SeriesMgr v3.1.17-20230307120939, running on Windows 11:

When I attempt to load a race (or load a .smn containing races), it crashes with the following unhelpful error:

```
Traceback (most recent call last):
  File "SeriesMgr.pyw", line 3, in <module>
  File "MainWin.py", line 961, in MainLoop
  File "argparse.py", line 1829, in parse_args
  File "argparse.py", line 2585, in error
  File "argparse.py", line 2555, in print_usage
  File "argparse.py", line 2566, in _print_message
AttributeError: 'NoneType' object has no attribute 'write'
```
Crucially, I'm not seeing this problem when running from source on Linux.

This is presumably related to the recent changes to read the races in parallel...

**Comment by kimble4** [comment]
Yep, that's fixed it for me.
